### ISSUE TITLE
The role defined for the function cannot be assumed by Lambda.

### ISSUE THREAD

**Issue by ashishsoni** [pdomala/LambdaCDDemo#1]
Any idea what is missing as i am getting below error
The role defined for the function cannot be assumed by Lambda. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: d98cedb2-1dd2-11e9-a5ce-a9684da8c5c4)
--

**Comment by pdomala** [comment]
Make sure you have lambda.amazonaws.com under Trust Relationships of your IAM role.
